# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_project/project_demo/project_demo.cache/wt [current_project]
set_property parent.project_path D:/vivado_project/project_demo/project_demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo d:/vivado_project/project_demo/project_demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_demolib {
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/imports/new/cla_test.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/cla_top.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/bit_slice.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/cla.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/cla_32.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/pg.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/sum.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/add_32.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/ie.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/alu.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/imports/new/test_add32.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/n_bits.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/full_adder.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/cla_adder.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/imports/new/test_alu.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/new/alu_ctr.v
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/imports/new/test_alu_ctr.v
}
read_verilog -library xil_defaultlib {
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/RISCVtop.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/ex.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/ex_mem.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/id.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/id_ex.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/if_id.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/inst_rom.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/mem.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/mem_wb.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/pc_reg.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/regfile.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/riscv.v}
  {C:/Users/57690/Desktop/3条指令RISC-V处理器verilog源代码/7.2.4 3条指令RISC-V处理器/test.v}
  D:/vivado_project/project_demo/project_demo.srcs/sources_1/imports/new/test_32add.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top test_alu_ctr -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef test_alu_ctr.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file test_alu_ctr_utilization_synth.rpt -pb test_alu_ctr_utilization_synth.pb"
